ATLIQ HARDWARE SALES INSIGHTS - DATA DISCOVERY QUERIES
-- Purpose: Explore schemas, check data health, and validate business records
-- ============================================================================

-- ----------------------------------------------------------------------------
-- 1. TRANSACTIONS TABLE EXPLORATION (Fact Table)
-- ----------------------------------------------------------------------------

-- Check the total number of transaction records logged in the database
SELECT COUNT(*) AS total_transaction_records 
FROM sales.transactions;

-- Inspect the first 10 rows to understand fields (amounts, currencies, dates)
SELECT * FROM sales.transactions 
LIMIT 10;

-- Identify currency anomalies (Find transactions recorded in USD vs INR)
-- *Note: This helps justify why we need currency normalization in Power BI
SELECT DISTINCT currency, COUNT(*) 
FROM sales.transactions 
GROUP BY currency;

-- Filter out bad data: Check if there are transactions with 0 or negative values
SELECT COUNT(*) AS corrupt_records 
FROM sales.transactions 
WHERE sales_amount <= 0;

2. CUSTOMERS TABLE EXPLORATION (Dimension Table)
-- ----------------------------------------------------------------------------

-- Check the total number of corporate clients AtliQ supplies to
SELECT COUNT(*) AS total_customers 
FROM sales.customers;

-- List unique customer types to see the business distribution (e.g., Brick & Mortar vs E-Commerce)
SELECT DISTINCT customer_type 
FROM sales.customers;

-- Find top 5 clients by examining customer details (e.g., finding specific store names like Excel Stores)
SELECT * FROM sales.customers 
LIMIT 5;

3. MARKETS TABLE EXPLORATION (Dimension Table)
-- ----------------------------------------------------------------------------

-- See all the operational zones and cities where AtliQ has regional offices
SELECT * FROM sales.markets;

-- Identify if there are any blank or international entries that don't belong to regional zones
SELECT DISTINCT zone 
FROM sales.markets;

-- Count how many distinct markets exist per zone (North, South, Central India)
SELECT zone, COUNT(market_name) AS total_markets 
FROM sales.markets 
GROUP BY zone;

4. MERGING & VERIFYING DATA (Business Insights Validation)
-- ----------------------------------------------------------------------------

-- Join transactions with markets to see total sales volume generated by the Delhi regional office
SELECT m.market_name, SUM(t.sales_amount) AS total_revenue
FROM sales.transactions t
JOIN sales.markets m ON t.market_code = m.markets_code
WHERE m.market_name = 'Delhi'
GROUP BY m.market_name;

-- Join transactions with customers to see the transactions details for 'Excel Stores'
SELECT c.custmer_name, t.* 
FROM sales.transactions t
JOIN sales.customers c ON t.customer_code = c.customers_code
WHERE c.custmer_name = 'Excel Stores'
LIMIT 10;